---
name: Update data
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  schedule:
    # - cron: "0 8 * * 1"
    - cron: "0 5 * * 2"

jobs:

  update:
    name: Update data
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies.
        run: |
          pip3 install beautifulsoup4 requests
      - name: Update data
        run: |
          python3 main.py >> README.md
      - name: Commit and push new data
        run: |
          git config --global user.name 'autobot'
          git config --global user.email 'autobot@users.noreply.github.com'
          git commit -am "Update data"
          git push
